"""Standard error codes for Step 0 state validation and routing gates."""

E_STATE_SCHEMA_INVALID = "E_STATE_SCHEMA_INVALID"
E_MISSING_REQUIRED_FIELD = "E_MISSING_REQUIRED_FIELD"
E_UNKNOWN_FIELD = "E_UNKNOWN_FIELD"
E_INVALID_FIELD_TYPE = "E_INVALID_FIELD_TYPE"
E_INVALID_STATUS = "E_INVALID_STATUS"
E_INVALID_ROUTE = "E_INVALID_ROUTE"
E_ENTRY_GATE_BLOCKED = "E_ENTRY_GATE_BLOCKED"
E_UNAUTHORIZED_FIELD_WRITE = "E_UNAUTHORIZED_FIELD_WRITE"

